# Form implementation generated from reading ui file '.\ui\FullScreenWindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1027, 683)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fcScrollArea = QtWidgets.QScrollArea(parent=Form)
        self.fcScrollArea.setMinimumSize(QtCore.QSize(800, 600))
        self.fcScrollArea.setStyleSheet("border-color: rgb(255, 255, 0);\n"
"background-color: rgb(238, 252, 255);")
        self.fcScrollArea.setWidgetResizable(True)
        self.fcScrollArea.setObjectName("fcScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 999, 600))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.fcScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.fcScrollArea)
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.fcTextEdit = QtWidgets.QLineEdit(parent=Form)
        self.fcTextEdit.setMinimumSize(QtCore.QSize(0, 29))
        self.fcTextEdit.setReadOnly(True)
        self.fcTextEdit.setObjectName("fcTextEdit")
        self.horizontalLayout.addWidget(self.fcTextEdit)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.fcButton = QtWidgets.QPushButton(parent=Form)
        self.fcButton.setMinimumSize(QtCore.QSize(0, 29))
        self.fcButton.setStyleSheet("font: 81 10pt \"JetBrains Mono NL ExtraBold\";")
        self.fcButton.setObjectName("fcButton")
        self.horizontalLayout.addWidget(self.fcButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.fcLabel = QtWidgets.QLabel(parent=Form)
        self.fcLabel.setMaximumSize(QtCore.QSize(275, 16777215))
        self.fcLabel.setText("")
        self.fcLabel.setObjectName("fcLabel")
        self.horizontalLayout.addWidget(self.fcLabel)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.fcFullScreenButton = QtWidgets.QPushButton(parent=Form)
        self.fcFullScreenButton.setMinimumSize(QtCore.QSize(0, 29))
        self.fcFullScreenButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/exit-fullscreen.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.fcFullScreenButton.setIcon(icon)
        self.fcFullScreenButton.setObjectName("fcFullScreenButton")
        self.horizontalLayout.addWidget(self.fcFullScreenButton)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.horizontalLayout.setStretch(1, 20)
        self.horizontalLayout.setStretch(3, 2)
        self.horizontalLayout.setStretch(5, 14)
        self.horizontalLayout.setStretch(7, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.setStretch(0, 20)
        self.verticalLayout_2.setStretch(2, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.setStretch(0, 10)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.fcButton.setText(_translate("Form", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
